name: Ruby

on:
  push:
  schedule:
    - cron: "59 11 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
        gem install bundler
    - name: Build and test with Rake
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake spec
